### PR TITLE
new projects for soumya

### PR DESCRIPTION
**Pull request by neelsoumya**
new projects for soumya

### CODE REVIEW

**Comment by apaleyes** [comment]
Thanks for the PR, @neelsoumya ! Unfortunately it will have to wait a little bit. Our page that lists student projects seems broken (https://mlatcl.github.io/internal/projects/ gives 404 at the moment), and I need to find out why before merging.

In meantime, if you click Deploy Preview link above (see the comment from Netlify bot) and navigate to `internal/projects/` there (in preview it works, but not in the main website), you'll see your project page does not show up in the list of available projects. Can you look into why?

**Comment by lawrennd** [comment]
Did this get fixed?

**Comment by lawrennd** [comment]
I've fixed that broken page.

**Comment by apaleyes** [comment]
Thanks @lawrennd , totally dropped the ball on this one!

@neelsoumya I've figured out the markup issues with the page, and modified it slightly. Hope that's ok with you

**Pull request merged**
