### PR TITLE
adding link to available software

### PR DESCRIPTION
**Pull request by cabrerac**
Adding a link to the tool for semi-automatic reviews.

### CODE REVIEW

**Comment by apaleyes** [comment]
Do you want to move it to mlatcl org, or keep it where it is now?

**Comment by apaleyes** [comment]
@cabrerac ping the question above

**Comment by cabrerac** [comment]
The current link is in the submitted paper to TOSEM. Let's wait for the reviews before we move it to mlatcl

**Comment by apaleyes** [comment]
i just realized that github will create redirects anyway, so it actually doesn't matter when we move!

**Pull request merged**
